/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

import java.awt.Color;
import motor.Operaciones;
import excepciones.ErrorAutor;
import javax.swing.DefaultComboBoxModel;
import motor.Autor;

/**
 *
 * @author launote
 */
public class AgregarAutor extends javax.swing.JFrame {
  AgregarLibro AL;
  ModificarLibro ML;
      /**
     * Creates new form AgregarAutor
     */
    public AgregarAutor(AgregarLibro A) {
        initComponents();
        Operaciones.consultarPaises((DefaultComboBoxModel)selectPais.getModel());
        AL=A;
    }
    
    public AgregarAutor(ModificarLibro A) {
        initComponents();
        Operaciones.consultarPaises((DefaultComboBoxModel)selectPais.getModel());
        ML=A;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        selectPais = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fNac = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        sexo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        buttonAgregar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infAutor = new javax.swing.JTextArea();
        errorNombre = new javax.swing.JLabel();
        errorApellido = new javax.swing.JLabel();
        errorFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Autor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(218, 216, 218));
        jPanel1.setFocusCycleRoot(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/PanelAgregarAutor.png"))); // NOI18N

        campoNombre.setBackground(new java.awt.Color(240, 238, 240));
        campoNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(153, 153, 153));
        campoNombre.setText(" Nombre");
        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });

        campoApellido.setBackground(new java.awt.Color(240, 238, 240));
        campoApellido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoApellido.setForeground(new java.awt.Color(153, 153, 153));
        campoApellido.setText(" Apellido");
        campoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoApellidoFocusLost(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(240, 238, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Pais: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(selectPais, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(240, 238, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de Nacimiento:");

        fNac.setMinSelectableDate(new java.util.Date(-14830977525000L));
        fNac.getDateEditor().setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fNac, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(240, 238, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        sexo.setName(""); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Sexo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregar.png"))); // NOI18N
        buttonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAgregarMouseExited(evt);
            }
        });

        infAutor.setBackground(new java.awt.Color(240, 238, 240));
        infAutor.setColumns(20);
        infAutor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        infAutor.setForeground(new java.awt.Color(153, 153, 153));
        infAutor.setRows(5);
        infAutor.setText(" Información del autor");
        infAutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                infAutorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                infAutorFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(infAutor);

        errorNombre.setForeground(new java.awt.Color(255, 0, 0));

        errorApellido.setForeground(new java.awt.Color(255, 0, 0));

        errorFecha.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(errorNombre)
                            .addComponent(errorApellido)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorFecha)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAgregar)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(errorNombre)
                .addGap(3, 3, 3)
                .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(errorApellido)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAgregar)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseClicked
        boolean agregado = false;
        try {
            agregado = Operaciones.agregarAutor(new Autor(campoNombre.getText(), campoApellido.getText(), 
            selectPais.getSelectedIndex(), fNac.getDate(), 
            sexo.getSelectedIndex(), infAutor.getText()));
            
            this.dispose();
            if(AL==null){
               ML.actualizarLA();
               ML.setEnabled(true);
            }else{
               AL.actualizar();
               AL.setEnabled(true);             
            }
            
        } catch (ErrorAutor e){
            //TODO Manejar reporte visual de error.
            if(e.isNombreCorto()){
                errorNombre.setText("Nombre Corto");
            } else if (e.isNombreLargo()){
                errorNombre.setText("Nombre Largo");
            } else if (e.isNombreInvalido()){
                errorNombre.setText("Nombre invalido");
            } else errorNombre.setText(null);
            if(e.isApellidoCorto()){
                errorApellido.setText("Apellido corto");
            } else if(e.isApellidoLargo()){
                errorApellido.setText("Apellido Largo");
            } 
            else if(e.isApellidoInvalido()){
                errorApellido.setText("Apellido Invalido");
            }else if(e.isAutorExistente()){
                errorApellido.setText("Autor Existe");
            } else errorApellido.setText(null);
            if(e.isFechaInvalida()){
                errorFecha.setText("Fecha invalida");
            } else errorFecha.setText(null);
        }
        if (agregado){
           this.dispose();
           if(AL==null){
             ML.setEnabled(true);
           }
           else
             AL.setEnabled(true);         
        }     
    }//GEN-LAST:event_buttonAgregarMouseClicked

    private void buttonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseEntered
         buttonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarFocus.png")));
    }//GEN-LAST:event_buttonAgregarMouseEntered

    private void buttonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgregarMouseExited
        buttonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregar.png")));
    }//GEN-LAST:event_buttonAgregarMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        if(AL==null)
           ML.setEnabled(true);
        else
           AL.setEnabled(true);
        
        
    }//GEN-LAST:event_formWindowClosing

    private void campoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusGained
           if (campoNombre.getText().equals(" Nombre")) {
            campoNombre.setText(null);
            campoNombre.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_campoNombreFocusGained

    private void campoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoApellidoFocusGained
              if (campoApellido.getText().equals(" Apellido")) {
            campoApellido.setText(null);
            campoApellido.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_campoApellidoFocusGained

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
        if (campoNombre.getText().equals("")){
             campoNombre.setText(" Nombre");
            campoNombre.setForeground(new java.awt.Color(153, 153, 153));
        }
       
    }//GEN-LAST:event_campoNombreFocusLost

    private void infAutorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_infAutorFocusGained
            if (infAutor.getText().equals(" Información del autor")) {
                infAutor.setText(null);
                infAutor.setForeground(Color.BLACK);
            }
            
    }//GEN-LAST:event_infAutorFocusGained

    private void campoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoApellidoFocusLost
         if (campoApellido.getText().equals("")){
             campoApellido.setText(" Apellido");
            campoApellido.setForeground(new java.awt.Color(153, 153, 153));
        }
         /*if (((javax.swing.JTextField) evt.getSource()).getName() != null) {
            try {
                lib.setPrecio(((javax.swing.JTextField) evt.getSource()).getText());
                modificar.setEnabled(true);
            } catch (ErrorLibro e) {
                //Procesar visualización de error.
                modificar.setEnabled(false);
                ((javax.swing.JTextField) evt.getSource()).requestFocus();
            }
        }*/
    }//GEN-LAST:event_campoApellidoFocusLost

    private void infAutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_infAutorFocusLost
          if (infAutor.getText().equals("")){
             infAutor.setText(" Información del autor");
             infAutor.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_infAutorFocusLost

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonAgregar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel errorApellido;
    private javax.swing.JLabel errorFecha;
    private javax.swing.JLabel errorNombre;
    private com.toedter.calendar.JDateChooser fNac;
    private javax.swing.JTextArea infAutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox selectPais;
    private javax.swing.JComboBox sexo;
    // End of variables declaration//GEN-END:variables
}
