/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

import excepciones.ErrorUsuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import motor.Carrito;
import motor.Usuario;


public class Identificarse extends javax.swing.JFrame {

    /**
     * Creates new form Identificarse
     */
    private boolean presiono=true;
    private boolean click=true;
    private boolean click2=true;
    Home home;
    
    public Identificarse(Home h) {
        initComponents();
        home=h;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JFormattedTextField();
        botonOlvidaste = new javax.swing.JLabel();
        botonEntrar = new javax.swing.JLabel();
        campoContraseña = new javax.swing.JPasswordField();
        errorLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Identificarse");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(218, 216, 218));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/PanelIdentificarse.png"))); // NOI18N

        campoUsuario.setBackground(new java.awt.Color(240, 238, 240));
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText(" Usuario");
        campoUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoUsuarioMouseClicked(evt);
            }
        });
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusLost(evt);
            }
        });
        campoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoUsuarioKeyPressed(evt);
            }
        });

        botonOlvidaste.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonOlvidaste.setForeground(new java.awt.Color(153, 153, 153));
        botonOlvidaste.setText("Olvidaste Contraseña ?");

        botonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonEntrar.png"))); // NOI18N
        botonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEntrarMouseExited(evt);
            }
        });

        campoContraseña.setBackground(new java.awt.Color(240, 238, 240));
        campoContraseña.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseña.setText("contraseña");
        campoContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoContraseñaFocusLost(evt);
            }
        });

        errorLog.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        errorLog.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLog)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(botonOlvidaste)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                            .addComponent(botonEntrar))
                        .addComponent(campoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoContraseña, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(errorLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEntrar)
                    .addComponent(botonOlvidaste))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
       
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusLost
        // TODO add your handling code here:
        if(campoUsuario.getText().equals("")){
            campoUsuario.setText(" Usuario");
            click=true;
            presiono=true;
            campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_campoUsuarioFocusLost

    private void campoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMouseClicked
        // TODO add your handling code here:
        if(click){
            campoUsuario.setText(null);
            click=false;
            campoUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoUsuarioMouseClicked

    private void campoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioKeyPressed
        // TODO add your handling code here:
        if (presiono){
            campoUsuario.setText(null);
            presiono=false;
            click=false;
            campoUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoUsuarioKeyPressed

    private void campoContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaFocusGained
        // TODO add your handling code here:
        if (click2){
            campoContraseña.setText(null);
            campoContraseña.setForeground(Color.black);
            click2=false;
        }
    }//GEN-LAST:event_campoContraseñaFocusGained

    private void campoContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaFocusLost
        // TODO add your handling code here:
        if(campoContraseña.getText().equals("")){
            campoContraseña.setText(" Contraseña");
            campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
            click2=true;
        }
        
    }//GEN-LAST:event_campoContraseñaFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        home.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void botonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrarMouseClicked
        try {
            home.setUsuario(new Usuario(campoUsuario.getText(), String.valueOf(campoContraseña.getPassword())));
            home.actualizar();
            home.carrito=new Carrito(home.getUsuario());
            this.dispose();
            home.setEnabled(true);
            this.errorLog.setVisible(false);
        } catch (ErrorUsuario e) {
            // Visualizar mensaje de error.
            this.errorLog.setText(" Usuario o Contraseña Incorrecta");
        }
    }//GEN-LAST:event_botonEntrarMouseClicked

    private void botonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrarMouseEntered
        // TODO add your handling code here:
        this.botonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonEntrarFocus.png")));
    }//GEN-LAST:event_botonEntrarMouseEntered

    private void botonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrarMouseExited
        // TODO add your handling code here:
        this.botonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonEntrar.png")));
    }//GEN-LAST:event_botonEntrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonEntrar;
    private javax.swing.JLabel botonOlvidaste;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JFormattedTextField campoUsuario;
    private javax.swing.JLabel errorLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
