/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

import motor.Operaciones;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import motor.Libro;

/**
 *
 * @author Manu
 */
public class ListadoLibros extends javax.swing.JFrame {
    VentanaAdmin VA;
    //Operaciones operaciones;
    private boolean click=true;
    /**
     * Creates new form ListadoDeLibros
     */
    public ListadoLibros(VentanaAdmin V) {
        initComponents();
        VA=V;
         //operaciones = new Operaciones();
        // operaciones.conectar();
         Operaciones.llenarTablaLibros((DefaultTableModel)TablaLibros.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListadoDeLibrosPanel = new javax.swing.JPanel();
        Encabezado = new javax.swing.JLabel();
        BotonModificar = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JLabel();
        jScrollPaneTablaLibros = new javax.swing.JScrollPane();
        TablaLibros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        campoBuscador = new javax.swing.JTextField();
        selectBuscar = new javax.swing.JComboBox();
        buttonBuscar = new javax.swing.JLabel();
        buttonListarTodo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de libros");
        setBackground(new java.awt.Color(1, 1, 1));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ListadoDeLibrosPanel.setBackground(new java.awt.Color(218, 216, 218));

        Encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/PanelListadoLibros.png"))); // NOI18N

        BotonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonModificar.png"))); // NOI18N
        BotonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonModificarMouseExited(evt);
            }
        });

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonEliminar.png"))); // NOI18N
        BotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseEntered(evt);
            }
        });

        jScrollPaneTablaLibros.setBackground(new java.awt.Color(218, 216, 218));

        TablaLibros.setBackground(new java.awt.Color(218, 216, 218));
        TablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isbn", "Titulo", "Apellido y Nombre del Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaLibros.setFocusable(false);
        TablaLibros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaLibros.setShowVerticalLines(false);
        TablaLibros.getTableHeader().setReorderingAllowed(false);
        TablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaLibrosMouseClicked(evt);
            }
        });
        jScrollPaneTablaLibros.setViewportView(TablaLibros);

        jPanel1.setBackground(new java.awt.Color(110, 34, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        campoBuscador.setBackground(new java.awt.Color(240, 238, 240));
        campoBuscador.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoBuscador.setForeground(new java.awt.Color(153, 153, 153));
        campoBuscador.setText("Buscador");
        campoBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBuscadorMouseClicked(evt);
            }
        });

        selectBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titulo del Libro", "Apellido del Autor" }));

        buttonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/Buscador2.png"))); // NOI18N
        buttonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBuscarMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBuscarMouseEntered(evt);
            }
        });

        buttonListarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonTodosLibros.png"))); // NOI18N
        buttonListarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonListarTodoMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonListarTodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonListarTodoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonBuscar)
                .addGap(18, 18, 18)
                .addComponent(buttonListarTodo)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoBuscador)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectBuscar)
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonListarTodo)
                            .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout ListadoDeLibrosPanelLayout = new javax.swing.GroupLayout(ListadoDeLibrosPanel);
        ListadoDeLibrosPanel.setLayout(ListadoDeLibrosPanelLayout);
        ListadoDeLibrosPanelLayout.setHorizontalGroup(
            ListadoDeLibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListadoDeLibrosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListadoDeLibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListadoDeLibrosPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTablaLibros)
                        .addGap(19, 19, 19))
                    .addGroup(ListadoDeLibrosPanelLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(BotonEliminar)
                        .addGap(46, 46, 46)
                        .addComponent(BotonModificar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(ListadoDeLibrosPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListadoDeLibrosPanelLayout.setVerticalGroup(
            ListadoDeLibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ListadoDeLibrosPanelLayout.createSequentialGroup()
                .addComponent(Encabezado)
                .addGap(102, 102, 102)
                .addGroup(ListadoDeLibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonModificar))
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ListadoDeLibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ListadoDeLibrosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseClicked
        if(this.TablaLibros.getSelectedRowCount()!=0){
             EliminarLibro venEli= new EliminarLibro (this);
             venEli.setLocationRelativeTo(this);
             venEli.setVisible(true);
             this.setEnabled(false);
        }

    }//GEN-LAST:event_BotonEliminarMouseClicked

    private void BotonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarMouseClicked
       if(this.TablaLibros.getSelectedRowCount()!=0){
            ModificarLibro ML=new ModificarLibro(this, new Libro(this.TablaLibros.getSelectedRowCount()));
            ML.setVisible(true);
            ML.setLocationRelativeTo(this);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_BotonModificarMouseClicked

    private void buttonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarMouseClicked
        // TODO add your handling code here:
        if("Titulo del Libro".equals(selectBuscar.getSelectedItem().toString())){
        Operaciones.buscadorTituloLibro((DefaultTableModel)TablaLibros.getModel(),campoBuscador.getText());
        }
        else{
            if("Apellido del Autor".equals(selectBuscar.getSelectedItem().toString())){
                 Operaciones.buscadorApellidoAutor((DefaultTableModel)TablaLibros.getModel(),campoBuscador.getText());
            }
        }
    }//GEN-LAST:event_buttonBuscarMouseClicked

    private void TablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaLibrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaLibrosMouseClicked

    private void buttonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarMouseEntered
        // TODO add your handling code here:
        buttonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/Buscador.png")));
    }//GEN-LAST:event_buttonBuscarMouseEntered

    private void buttonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarMouseExited
        // TODO add your handling code here:
         buttonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/Buscador2.png")));
    }//GEN-LAST:event_buttonBuscarMouseExited

    private void buttonListarTodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonListarTodoMouseEntered
        // TODO add your handling code here:
        buttonListarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonTodosLibrosFocus.png")));
    }//GEN-LAST:event_buttonListarTodoMouseEntered

    private void buttonListarTodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonListarTodoMouseExited
        // TODO add your handling code here:
        buttonListarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonTodosLibros.png")));
    }//GEN-LAST:event_buttonListarTodoMouseExited

    private void buttonListarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonListarTodoMouseClicked
        // TODO add your handling code here:
       Operaciones.llenarTablaLibros((DefaultTableModel)TablaLibros.getModel());
    }//GEN-LAST:event_buttonListarTodoMouseClicked

    private void campoBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBuscadorMouseClicked
        // TODO add your handling code here:
              if (click) {
                campoBuscador.setText(null);
                click=false;
                campoBuscador.setForeground(Color.black);
    }
    }//GEN-LAST:event_campoBuscadorMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        VA.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void BotonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseEntered
        // TODO add your handling code here:
          BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonEliminarFocus.png")));
    }//GEN-LAST:event_BotonEliminarMouseEntered

    private void BotonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseExited
        // TODO add your handling code here:
        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonEliminar.png")));
    }//GEN-LAST:event_BotonEliminarMouseExited

    private void BotonModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarMouseEntered
        // TODO add your handling code here:
        BotonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonModificarFocus.png")));
    }//GEN-LAST:event_BotonModificarMouseEntered

    private void BotonModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarMouseExited
        // TODO add your handling code here:
        BotonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonModificar.png")));
    }//GEN-LAST:event_BotonModificarMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonEliminar;
    private javax.swing.JLabel BotonModificar;
    private javax.swing.JLabel Encabezado;
    private javax.swing.JPanel ListadoDeLibrosPanel;
    private javax.swing.JTable TablaLibros;
    private javax.swing.JLabel buttonBuscar;
    private javax.swing.JLabel buttonListarTodo;
    private javax.swing.JTextField campoBuscador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneTablaLibros;
    private javax.swing.JComboBox selectBuscar;
    // End of variables declaration//GEN-END:variables
}
