/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

import java.awt.Color;
import motor.Usuario;


public class ModificarDatosUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ModificarDatosUsuario
     */
    private boolean presiono=true;
    private boolean click1=true;
    private boolean click2=true;
    private boolean click3=true;
    private boolean click4=true;
    private boolean click5=true;
    private boolean click6=true;
    private boolean click7=true;
    private boolean click8=true;
    private boolean click9=true;
    private boolean click10=true;
    private Home home;
    private Usuario usuario;
    
    
    public ModificarDatosUsuario(Home h, Usuario usuario) {
        this.usuario = usuario;
        this.home=h;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        tablaDatos = new javax.swing.JTabbedPane();
        paneModificarlDatos = new javax.swing.JPanel();
        campoProvincia = new javax.swing.JTextField();
        campoCiudad = new javax.swing.JTextField();
        campoCodigoPostal = new javax.swing.JTextField();
        campoCalle = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoNro = new javax.swing.JTextField();
        campoEmail = new javax.swing.JFormattedTextField();
        panelCambiarContraseña = new javax.swing.JPanel();
        campoContraseñaActual = new javax.swing.JPasswordField();
        campoContraseñaNueva = new javax.swing.JPasswordField();
        campoConfirmarContraseña = new javax.swing.JPasswordField();
        labelContraseñaActual = new javax.swing.JLabel();
        labelContraseñaNueva = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        nombreUsuario1 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();
        botonModificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de cuenta");
        setPreferredSize(new java.awt.Dimension(540, 175));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(218, 216, 218));

        paneModificarlDatos.setBackground(new java.awt.Color(218, 216, 218));

        campoProvincia.setBackground(new java.awt.Color(240, 238, 240));
        campoProvincia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoProvincia.setForeground(new java.awt.Color(153, 153, 153));
        campoProvincia.setText("CAMBIAR POR COMBOBOX");
        campoProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoProvinciaMouseClicked(evt);
            }
        });
        campoProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoProvinciaFocusLost(evt);
            }
        });
        campoProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoProvinciaKeyPressed(evt);
            }
        });

        campoCiudad.setBackground(new java.awt.Color(240, 238, 240));
        campoCiudad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoCiudad.setForeground(new java.awt.Color(153, 153, 153));
        campoCiudad.setText(usuario.getDireccion().getLocalidad());
        campoCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCiudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCiudadFocusLost(evt);
            }
        });

        campoCodigoPostal.setBackground(new java.awt.Color(240, 238, 240));
        campoCodigoPostal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoCodigoPostal.setForeground(new java.awt.Color(153, 153, 153));
        campoCodigoPostal.setText(usuario.getDireccion().getCodigoPostal());
        campoCodigoPostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCodigoPostalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoPostalFocusLost(evt);
            }
        });

        campoCalle.setBackground(new java.awt.Color(240, 238, 240));
        campoCalle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoCalle.setForeground(new java.awt.Color(153, 153, 153));
        campoCalle.setText(usuario.getDireccion().getCalle());
        campoCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCalleFocusLost(evt);
            }
        });

        campoTelefono.setBackground(new java.awt.Color(240, 238, 240));
        campoTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoTelefono.setForeground(new java.awt.Color(153, 153, 153));
        campoTelefono.setText(usuario.getTelefono());
        campoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefonoFocusLost(evt);
            }
        });

        campoNro.setBackground(new java.awt.Color(240, 238, 240));
        campoNro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoNro.setForeground(new java.awt.Color(153, 153, 153));
        campoNro.setText(usuario.getDireccion().getAltura());
        campoNro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNroFocusLost(evt);
            }
        });

        campoEmail.setBackground(new java.awt.Color(240, 238, 240));
        campoEmail.setForeground(new java.awt.Color(153, 153, 153));
        campoEmail.setText(usuario.getEmail());
        campoEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout paneModificarlDatosLayout = new javax.swing.GroupLayout(paneModificarlDatos);
        paneModificarlDatos.setLayout(paneModificarlDatosLayout);
        paneModificarlDatosLayout.setHorizontalGroup(
            paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificarlDatosLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoCodigoPostal, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(paneModificarlDatosLayout.createSequentialGroup()
                        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoNro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(campoProvincia)
                    .addComponent(campoCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(campoEmail))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        paneModificarlDatosLayout.setVerticalGroup(
            paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificarlDatosLayout.createSequentialGroup()
                .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaDatos.addTab("Modificar Datos", paneModificarlDatos);

        panelCambiarContraseña.setBackground(new java.awt.Color(218, 216, 218));

        campoContraseñaActual.setBackground(new java.awt.Color(240, 238, 240));
        campoContraseñaActual.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoContraseñaActual.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseñaActual.setText("asdasd");
        campoContraseñaActual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoContraseñaActualFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoContraseñaActualFocusLost(evt);
            }
        });

        campoContraseñaNueva.setBackground(new java.awt.Color(240, 238, 240));
        campoContraseñaNueva.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoContraseñaNueva.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseñaNueva.setText("asdasd");
        campoContraseñaNueva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoContraseñaNuevaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoContraseñaNuevaFocusLost(evt);
            }
        });

        campoConfirmarContraseña.setBackground(new java.awt.Color(240, 238, 240));
        campoConfirmarContraseña.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoConfirmarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoConfirmarContraseña.setText("asdasd");
        campoConfirmarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConfirmarContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoConfirmarContraseñaFocusLost(evt);
            }
        });

        labelContraseñaActual.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelContraseñaActual.setText("Contraseña Actual:");

        labelContraseñaNueva.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelContraseñaNueva.setText("Contaseña Nueva:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Confirmar Contaseña:");

        javax.swing.GroupLayout panelCambiarContraseñaLayout = new javax.swing.GroupLayout(panelCambiarContraseña);
        panelCambiarContraseña.setLayout(panelCambiarContraseñaLayout);
        panelCambiarContraseñaLayout.setHorizontalGroup(
            panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCambiarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCambiarContraseñaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCambiarContraseñaLayout.createSequentialGroup()
                        .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContraseñaActual)
                            .addComponent(labelContraseñaNueva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoContraseñaNueva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoContraseñaActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 84, Short.MAX_VALUE))
        );
        panelCambiarContraseñaLayout.setVerticalGroup(
            panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContraseñaActual))
                .addGap(67, 67, 67)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContraseñaNueva))
                .addGap(18, 18, 18)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tablaDatos.addTab("Cambiar Contraseña", panelCambiarContraseña);

        botonGuardar.setText("Guardar");
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tablaDatos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGuardar)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(218, 216, 218));

        jLabel2.setText("Cuenta de Usuario");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        apellido1.setText(usuario.getApellido());

        nombre1.setText(usuario.getNombre());

        nombreUsuario1.setText(usuario.getUsuario());

        fecha1.setText(usuario.getFechaNacimiento());

        botonModificar.setText("MODIFICAR");
        botonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fecha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificar)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreUsuario1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nombre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellido1)))
                        .addGap(215, 215, 215))))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre1)
                    .addComponent(apellido1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha1)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoProvinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoProvinciaKeyPressed
        // TODO add your handling code here:
        if(presiono){
            presiono=false;
            campoProvincia.setText(null);
            campoProvincia.setForeground(Color.black);
            click1=false;
        }
    }//GEN-LAST:event_campoProvinciaKeyPressed

    private void campoProvinciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoProvinciaMouseClicked
        // TODO add your handling code here:
        if(click1){
            presiono=false;
            campoProvincia.setText(null);
            campoProvincia.setForeground(Color.black);
            click1=false;
        }
    }//GEN-LAST:event_campoProvinciaMouseClicked

    private void campoProvinciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoProvinciaFocusLost
        // TODO add your handling code here:
        if(campoProvincia.getText().equals("")){
            campoProvincia.setText(" Provincia");
            click1=true;
            presiono=true;
            campoProvincia.setForeground((new java.awt.Color(153, 153, 153)));
        }
    }//GEN-LAST:event_campoProvinciaFocusLost

    private void campoCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCiudadFocusGained
        // TODO add your handling code here:
        if(click2){
            campoCiudad.setText(null);
            click2=false;
            campoCiudad.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoCiudadFocusGained

    private void campoCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCalleFocusGained
        // TODO add your handling code here:
        if(click3){
            campoCalle.setText(null);
            click3=false;
            campoCalle.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoCalleFocusGained

    private void campoNroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNroFocusGained
        // TODO add your handling code here:
        if(click4){
            campoNro.setText(null);
            click4=false;
            campoNro.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoNroFocusGained

    private void campoTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonoFocusGained
        // TODO add your handling code here:
        if(click5){
            campoTelefono.setText(null);
            click5=false;
            campoTelefono.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoTelefonoFocusGained

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
        // TODO add your handling code here:
        if(click6){
            campoEmail.setText(null);
            click6=false;
            campoEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoEmailFocusGained

    private void campoCodigoPostalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoPostalFocusGained
        // TODO add your handling code here:
        if(click7){
            campoCodigoPostal.setText(null);
            click7=false;
            campoCodigoPostal.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoCodigoPostalFocusGained

    private void campoCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCiudadFocusLost
        if(campoCiudad.getText().equals("")){
            campoCiudad.setText(" Ciudad");
            campoCiudad.setForeground((new java.awt.Color(153, 153, 153)));
            click2=true;
        }
    }//GEN-LAST:event_campoCiudadFocusLost

    private void campoCodigoPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoPostalFocusLost
        // TODO add your handling code here:
        if(campoCodigoPostal.getText().equals("")){
            campoCodigoPostal.setText(" Codigo Postal");
            campoCodigoPostal.setForeground((new java.awt.Color(153, 153, 153)));
            click7=true;
        }
    }//GEN-LAST:event_campoCodigoPostalFocusLost

    private void campoCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCalleFocusLost
        // TODO add your handling code here:
        if(campoCalle.getText().equals("")){
            campoCalle.setText(" Calle");
            campoCalle.setForeground((new java.awt.Color(153, 153, 153)));
            click3=true;
        }
    }//GEN-LAST:event_campoCalleFocusLost

    private void campoNroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNroFocusLost
        // TODO add your handling code here:
        if(campoNro.getText().equals("")){
            campoNro.setText(" Número");
            campoNro.setForeground((new java.awt.Color(153, 153, 153)));
            click4=true;
        }
    }//GEN-LAST:event_campoNroFocusLost

    private void campoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonoFocusLost
        // TODO add your handling code here:
        if(campoTelefono.getText().equals("")){
            campoTelefono.setText(" Teléfono");
            campoTelefono.setForeground((new java.awt.Color(153, 153, 153)));
            click5=true;
        }
    }//GEN-LAST:event_campoTelefonoFocusLost

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        // TODO add your handling code here:
        if(campoEmail.getText().equals("")){
            campoEmail.setText(" E-mail");
            campoEmail.setForeground((new java.awt.Color(153, 153, 153)));
            click6=true;
        }
    }//GEN-LAST:event_campoEmailFocusLost

    private void campoContraseñaActualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaActualFocusLost
        // TODO add your handling code here:
        if(campoContraseñaActual.getText().equals("")){
            campoContraseñaActual.setText(" asdasd");
            campoContraseñaActual.setForeground((new java.awt.Color(153, 153, 153)));
            click8=true;
        }
    }//GEN-LAST:event_campoContraseñaActualFocusLost

    private void campoContraseñaNuevaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaNuevaFocusLost
        // TODO add your handling code here:
        if(campoContraseñaNueva.getText().equals("")){
            campoContraseñaNueva.setText(" asdasd");
            campoContraseñaNueva.setForeground((new java.awt.Color(153, 153, 153)));
            click9=true;
        }
    }//GEN-LAST:event_campoContraseñaNuevaFocusLost

    private void campoConfirmarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarContraseñaFocusLost
        // TODO add your handling code here:
        if(campoConfirmarContraseña.getText().equals("")){
            campoConfirmarContraseña.setText(" asdasd");
            campoConfirmarContraseña.setForeground((new java.awt.Color(153, 153, 153)));
            click10=true;
        }
    }//GEN-LAST:event_campoConfirmarContraseñaFocusLost

    private void campoContraseñaActualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaActualFocusGained
        // TODO add your handling code here:
        if(click8){
            campoContraseñaActual.setText(null);
            click8=false;
            campoContraseñaActual.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoContraseñaActualFocusGained

    private void campoContraseñaNuevaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaNuevaFocusGained
        // TODO add your handling code here:
        if(click9){
            campoContraseñaNueva.setText(null);
            click9=false;
            campoContraseñaNueva.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoContraseñaNuevaFocusGained

    private void campoConfirmarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarContraseñaFocusGained
        // TODO add your handling code here:
        if(click10){
            campoConfirmarContraseña.setText(null);
            click10=false;
            campoConfirmarContraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoConfirmarContraseñaFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        home.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void botonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        this.setSize(540, 575);
        this.setLocationRelativeTo(home);
        
    }//GEN-LAST:event_botonModificarMouseClicked

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        usuario.modificar();
    }//GEN-LAST:event_botonGuardarMouseClicked

 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido1;
    private javax.swing.JLabel botonGuardar;
    private javax.swing.JLabel botonModificar;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JTextField campoCodigoPostal;
    private javax.swing.JPasswordField campoConfirmarContraseña;
    private javax.swing.JPasswordField campoContraseñaActual;
    private javax.swing.JPasswordField campoContraseñaNueva;
    private javax.swing.JFormattedTextField campoEmail;
    private javax.swing.JTextField campoNro;
    private javax.swing.JTextField campoProvincia;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel fecha1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelContraseñaActual;
    private javax.swing.JLabel labelContraseñaNueva;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombreUsuario1;
    private javax.swing.JPanel paneModificarlDatos;
    private javax.swing.JPanel panelCambiarContraseña;
    private javax.swing.JTabbedPane tablaDatos;
    // End of variables declaration//GEN-END:variables
}
