/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

import java.awt.Color;


public class ModificarDatosUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ModificarDatosUsuario
     */
    private boolean presiono=true;
    private boolean click1=true;
    private boolean click2=true;
    private boolean click3=true;
    private boolean click4=true;
    private boolean click5=true;
    private boolean click6=true;
    private boolean click7=true;
    Home home;
    
    public ModificarDatosUsuario(Home h) {
        initComponents();
        home=h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tablaDatos = new javax.swing.JTabbedPane();
        paneModificarlDatos = new javax.swing.JPanel();
        campoProvincia = new javax.swing.JTextField();
        campoProvincia1 = new javax.swing.JTextField();
        campoProvincia2 = new javax.swing.JTextField();
        campoCalle = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoNro = new javax.swing.JTextField();
        campoEmail = new javax.swing.JFormattedTextField();
        panelCambiarContraseña = new javax.swing.JPanel();
        campoContraseñaActual = new javax.swing.JPasswordField();
        campoContraseñaNueva = new javax.swing.JPasswordField();
        campoConfirmarContraseña = new javax.swing.JPasswordField();
        botonGuardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Datos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(218, 216, 218));

        jLabel1.setText("Cuenta de Usuario");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombre.setText("Nombre");

        apellido.setText("Apellido");

        nombreUsuario.setText("nombre de Usuario");

        fecha.setText("fecha de nacimiento");

        paneModificarlDatos.setBackground(new java.awt.Color(218, 216, 218));

        campoProvincia.setBackground(new java.awt.Color(240, 238, 240));
        campoProvincia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoProvincia.setForeground(new java.awt.Color(153, 153, 153));
        campoProvincia.setText("Provincia");
        campoProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoProvinciaMouseClicked(evt);
            }
        });
        campoProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoProvinciaKeyPressed(evt);
            }
        });

        campoProvincia1.setBackground(new java.awt.Color(240, 238, 240));
        campoProvincia1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoProvincia1.setForeground(new java.awt.Color(153, 153, 153));
        campoProvincia1.setText("Ciudad");

        campoProvincia2.setBackground(new java.awt.Color(240, 238, 240));
        campoProvincia2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoProvincia2.setForeground(new java.awt.Color(153, 153, 153));
        campoProvincia2.setText("Codigo Pastal");

        campoCalle.setBackground(new java.awt.Color(240, 238, 240));
        campoCalle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoCalle.setForeground(new java.awt.Color(153, 153, 153));
        campoCalle.setText("Calle");

        campoTelefono.setBackground(new java.awt.Color(240, 238, 240));
        campoTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoTelefono.setForeground(new java.awt.Color(153, 153, 153));
        campoTelefono.setText("Telefono");

        campoNro.setBackground(new java.awt.Color(240, 238, 240));
        campoNro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoNro.setForeground(new java.awt.Color(153, 153, 153));
        campoNro.setText("Nro");

        campoEmail.setBackground(new java.awt.Color(240, 238, 240));
        campoEmail.setForeground(new java.awt.Color(153, 153, 153));
        campoEmail.setText("email");
        campoEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneModificarlDatosLayout = new javax.swing.GroupLayout(paneModificarlDatos);
        paneModificarlDatos.setLayout(paneModificarlDatosLayout);
        paneModificarlDatosLayout.setHorizontalGroup(
            paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificarlDatosLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoProvincia2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(paneModificarlDatosLayout.createSequentialGroup()
                        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoNro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(campoProvincia)
                    .addComponent(campoProvincia1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(campoEmail))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        paneModificarlDatosLayout.setVerticalGroup(
            paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificarlDatosLayout.createSequentialGroup()
                .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoProvincia1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoProvincia2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneModificarlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaDatos.addTab("Modificar Datos", paneModificarlDatos);

        panelCambiarContraseña.setBackground(new java.awt.Color(218, 216, 218));

        campoContraseñaActual.setBackground(new java.awt.Color(240, 238, 240));
        campoContraseñaActual.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoContraseñaActual.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseñaActual.setText("Contraseña Actual");

        campoContraseñaNueva.setBackground(new java.awt.Color(240, 238, 240));
        campoContraseñaNueva.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoContraseñaNueva.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseñaNueva.setText("Contraseña Nueva");

        campoConfirmarContraseña.setBackground(new java.awt.Color(240, 238, 240));
        campoConfirmarContraseña.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        campoConfirmarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoConfirmarContraseña.setText("Confirmar Contraseña");

        javax.swing.GroupLayout panelCambiarContraseñaLayout = new javax.swing.GroupLayout(panelCambiarContraseña);
        panelCambiarContraseña.setLayout(panelCambiarContraseñaLayout);
        panelCambiarContraseñaLayout.setHorizontalGroup(
            panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelCambiarContraseñaLayout.setVerticalGroup(
            panelCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarContraseñaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(campoContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(campoContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tablaDatos.addTab("Cambiar Contraseña", panelCambiarContraseña);

        botonGuardar.setText("Guardar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha)
                    .addComponent(nombreUsuario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(tablaDatos)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(apellido))
                .addGap(18, 18, 18)
                .addComponent(nombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(fecha)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoProvinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoProvinciaKeyPressed
        // TODO add your handling code here:
        if(presiono){
            presiono=false;
            campoProvincia.setText(null);
            campoProvincia.setForeground(Color.black);
            click1=false;
        }
    }//GEN-LAST:event_campoProvinciaKeyPressed

    private void campoProvinciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoProvinciaMouseClicked
        // TODO add your handling code here:
        if(click1){
            presiono=false;
            campoProvincia.setText(null);
            campoProvincia.setForeground(Color.black);
            click1=false;
        }
    }//GEN-LAST:event_campoProvinciaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        home.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel botonGuardar;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JPasswordField campoConfirmarContraseña;
    private javax.swing.JPasswordField campoContraseñaActual;
    private javax.swing.JPasswordField campoContraseñaNueva;
    private javax.swing.JFormattedTextField campoEmail;
    private javax.swing.JTextField campoNro;
    private javax.swing.JTextField campoProvincia;
    private javax.swing.JTextField campoProvincia1;
    private javax.swing.JTextField campoProvincia2;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JPanel paneModificarlDatos;
    private javax.swing.JPanel panelCambiarContraseña;
    private javax.swing.JTabbedPane tablaDatos;
    // End of variables declaration//GEN-END:variables
}
