/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

/**
 *
 * @author Manu
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaAdminPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarLibro = new javax.swing.JLabel();
        botonVisualizarLibro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Administrador");
        setResizable(false);

        VentanaAdminPanel.setBackground(new java.awt.Color(218, 216, 218));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/PanelAdministrador.png"))); // NOI18N

        botonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarLibro.png"))); // NOI18N
        botonAgregarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAgregarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAgregarLibroMouseExited(evt);
            }
        });

        botonVisualizarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonVisualizarLibros.png"))); // NOI18N
        botonVisualizarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVisualizarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVisualizarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVisualizarLibroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout VentanaAdminPanelLayout = new javax.swing.GroupLayout(VentanaAdminPanel);
        VentanaAdminPanel.setLayout(VentanaAdminPanelLayout);
        VentanaAdminPanelLayout.setHorizontalGroup(
            VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaAdminPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(botonAgregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVisualizarLibro)
                .addGap(72, 72, 72))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaAdminPanelLayout.setVerticalGroup(
            VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaAdminPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregarLibro)
                    .addComponent(botonVisualizarLibro))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarLibroMouseClicked
        // TODO add your handling code here:
        AgregarLibro AL=new AgregarLibro(this);
        AL.setLocationRelativeTo(this);
        AL.setVisible(true);
        this.setEnabled(false);
        
        /*;*/
    }//GEN-LAST:event_botonAgregarLibroMouseClicked

    private void botonAgregarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarLibroMouseEntered
        // TODO add your handling code here:
        botonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarLibroFocus.png")));
        
    }//GEN-LAST:event_botonAgregarLibroMouseEntered

    private void botonVisualizarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVisualizarLibroMouseClicked
        // TODO add your handling code here:
        ListadoLibros LL=new ListadoLibros(this);
        LL.setVisible(true);
        LL.setLocationRelativeTo(this);
        this.setEnabled(false);
    }//GEN-LAST:event_botonVisualizarLibroMouseClicked

    private void botonVisualizarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVisualizarLibroMouseEntered
        // TODO add your handling code here:
         botonVisualizarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonVisualizarLibrosFocus.png")));
    }//GEN-LAST:event_botonVisualizarLibroMouseEntered

    private void botonAgregarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarLibroMouseExited
        // TODO add your handling code here:
         botonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarLibro.png")));
    }//GEN-LAST:event_botonAgregarLibroMouseExited

    private void botonVisualizarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVisualizarLibroMouseExited
        // TODO add your handling code here:
        botonVisualizarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonVisualizarLibros.png")));
    }//GEN-LAST:event_botonVisualizarLibroMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VentanaAdminPanel;
    private javax.swing.JLabel botonAgregarLibro;
    private javax.swing.JLabel botonVisualizarLibro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
