/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

/**
 *
 * @author Franco
 */
public class VentanaDetalle extends javax.swing.JFrame {
    private Home home;
    /**
     * Creates new form VentanaDetalle
     */
    public VentanaDetalle(Home home) {
        initComponents();
        this.home=home;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDetalle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelAutor = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();
        labelClasificacion = new javax.swing.JLabel();
        labelFormato = new javax.swing.JLabel();
        labelPaginas = new javax.swing.JLabel();
        labelPublicacion = new javax.swing.JLabel();
        labelIdioma = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        etiquetaDetalle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(218, 216, 218));

        panelDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/panelDetalle.JPG"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelImagen.setPreferredSize(new java.awt.Dimension(128, 162));

        labelTitulo.setBackground(new java.awt.Color(153, 153, 153));
        labelTitulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        labelTitulo.setText("aca titulo");

        labelAutor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelAutor.setForeground(new java.awt.Color(153, 153, 153));
        labelAutor.setText("Auto:");

        labelPrecio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelPrecio.setForeground(new java.awt.Color(0, 51, 255));
        labelPrecio.setText("Precio: $");

        labelIsbn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelIsbn.setForeground(new java.awt.Color(153, 153, 153));
        labelIsbn.setText("I.S.B.N:");

        labelClasificacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelClasificacion.setForeground(new java.awt.Color(153, 153, 153));
        labelClasificacion.setText("Clasificacion:");

        labelFormato.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelFormato.setForeground(new java.awt.Color(153, 153, 153));
        labelFormato.setText("Formato:");

        labelPaginas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelPaginas.setForeground(new java.awt.Color(153, 153, 153));
        labelPaginas.setText("Paginas:");

        labelPublicacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelPublicacion.setForeground(new java.awt.Color(153, 153, 153));
        labelPublicacion.setText("Publicacion:");

        labelIdioma.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelIdioma.setForeground(new java.awt.Color(153, 153, 153));
        labelIdioma.setText("Idioma:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addComponent(labelClasificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIdioma)
                            .addComponent(labelPublicacion)
                            .addComponent(labelPaginas)
                            .addComponent(labelFormato)
                            .addComponent(labelIsbn)
                            .addComponent(labelAutor)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(labelPrecio)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(labelPrecio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelAutor)
                        .addGap(4, 4, 4)
                        .addComponent(labelIsbn)
                        .addGap(1, 1, 1)
                        .addComponent(labelClasificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFormato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPublicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIdioma)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaDetalle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        etiquetaDetalle.setForeground(new java.awt.Color(153, 153, 153));
        etiquetaDetalle.setText("Detalles");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(etiquetaDetalle)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        areaTexto.setForeground(new java.awt.Color(153, 153, 153));
        areaTexto.setLineWrap(true);
        areaTexto.setRows(5);
        areaTexto.setFocusable(false);
        jScrollPane2.setViewportView(areaTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        this.home.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JLabel etiquetaDetalle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelClasificacion;
    private javax.swing.JLabel labelFormato;
    private javax.swing.JLabel labelIdioma;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelPaginas;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelPublicacion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel panelDetalle;
    // End of variables declaration//GEN-END:variables
}
