/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

/**
 *
 * @author Manu
 */
public class VentanaAdmin extends javax.swing.JFrame {

    Home home;
    
    public VentanaAdmin(Home h) {
        initComponents();
        home=h;
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaAdminPanel = new javax.swing.JPanel();
        encabezado = new javax.swing.JLabel();
        botonAgregarLibro = new javax.swing.JLabel();
        botonVisualizarLibro = new javax.swing.JLabel();
        botonPedidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Administrador");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        VentanaAdminPanel.setBackground(new java.awt.Color(218, 216, 218));

        encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/PanelAdministrador.png"))); // NOI18N

        botonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarLibro.png"))); // NOI18N
        botonAgregarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAgregarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAgregarLibroMouseExited(evt);
            }
        });

        botonVisualizarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonVisualizarLibros.png"))); // NOI18N
        botonVisualizarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVisualizarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVisualizarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVisualizarLibroMouseExited(evt);
            }
        });

        botonPedidos.setText("PEDIDOS");
        botonPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPedidosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentanaAdminPanelLayout = new javax.swing.GroupLayout(VentanaAdminPanel);
        VentanaAdminPanel.setLayout(VentanaAdminPanelLayout);
        VentanaAdminPanelLayout.setHorizontalGroup(
            VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VentanaAdminPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarLibro)
                    .addComponent(botonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVisualizarLibro)
                .addGap(72, 72, 72))
        );
        VentanaAdminPanelLayout.setVerticalGroup(
            VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaAdminPanelLayout.createSequentialGroup()
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregarLibro)
                    .addComponent(botonVisualizarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(botonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarLibroMouseClicked
        // TODO add your handling code here:
        AgregarLibro AL=new AgregarLibro(this);
        AL.setLocationRelativeTo(this);
        AL.setVisible(true);
        this.setEnabled(false);
        
        /*;*/
    }//GEN-LAST:event_botonAgregarLibroMouseClicked

    private void botonAgregarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarLibroMouseEntered
        // TODO add your handling code here:
        botonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarLibroFocus.png")));
        
    }//GEN-LAST:event_botonAgregarLibroMouseEntered

    private void botonVisualizarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVisualizarLibroMouseClicked
        // TODO add your handling code here:
        ListadoLibros LL=new ListadoLibros(this);
        LL.setLocationRelativeTo(this);
        LL.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_botonVisualizarLibroMouseClicked

    private void botonVisualizarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVisualizarLibroMouseEntered
        // TODO add your handling code here:
         botonVisualizarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonVisualizarLibrosFocus.png")));
    }//GEN-LAST:event_botonVisualizarLibroMouseEntered

    private void botonAgregarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarLibroMouseExited
        // TODO add your handling code here:
         botonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonAgregarLibro.png")));
    }//GEN-LAST:event_botonAgregarLibroMouseExited

    private void botonVisualizarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVisualizarLibroMouseExited
        // TODO add your handling code here:
        botonVisualizarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagen/Resource/ButtonVisualizarLibros.png")));
    }//GEN-LAST:event_botonVisualizarLibroMouseExited

    private void botonPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPedidosMouseClicked
        // TODO add your handling code here:
        PedidosAdmin PA=new PedidosAdmin(this);
        PA.setLocationRelativeTo(this);
        PA.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_botonPedidosMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        home.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VentanaAdminPanel;
    private javax.swing.JLabel botonAgregarLibro;
    private javax.swing.JLabel botonPedidos;
    private javax.swing.JLabel botonVisualizarLibro;
    private javax.swing.JLabel encabezado;
    // End of variables declaration//GEN-END:variables
}
