package cookbookinterfaz;


import javax.swing.DefaultComboBoxModel;

import Operaciones.Operaciones;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

        
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author launote
 */
public class AgregarLibro extends javax.swing.JFrame {
  Operaciones operaciones;
  VentanaAdmin VA;
    /**
     * Creates new form NewJFrame
     */
    private boolean click1 = true;
    private boolean click2 = true;
    private boolean click3 = true;
    private boolean click4 = true;
    private boolean click5 = true;
    private boolean click6 = true;
    private boolean click7 = true;
    
    public AgregarLibro(VentanaAdmin V) {
        initComponents();
        VA=V;
         //operaciones = new Operaciones();
        // operaciones.conectar();
         //operaciones.consultarIdioma((DefaultComboBoxModel)jComboBox1.getModel());
         Operaciones.llenarListaAutores(listaAutores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarLibroPanel = new javax.swing.JPanel();
        CampoIsbn = new javax.swing.JTextField();
        CampoCantPag = new javax.swing.JTextField();
        CampoPrecio = new javax.swing.JTextField();
        CampoTitulo = new javax.swing.JTextField();
        CampoFecha = new javax.swing.JTextField();
        Encabezado = new javax.swing.JLabel();
        jScrollPaneAreaDesc = new javax.swing.JScrollPane();
        AreaDesc = new javax.swing.JTextArea();
        Agregar = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Añadir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAutores = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelImagen = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Libro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        AgregarLibroPanel.setBackground(new java.awt.Color(218, 216, 218));
        AgregarLibroPanel.setToolTipText("");
        AgregarLibroPanel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        CampoIsbn.setBackground(new java.awt.Color(240, 238, 240));
        CampoIsbn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CampoIsbn.setForeground(new java.awt.Color(153, 153, 153));
        CampoIsbn.setText(" I.S.B.N");
        CampoIsbn.setToolTipText("Solo numeros");
        CampoIsbn.setPreferredSize(new java.awt.Dimension(165, 34));
        CampoIsbn.setSelectionColor(new java.awt.Color(110, 34, 83));
        CampoIsbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoIsbnMouseClicked(evt);
            }
        });
        CampoIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIsbnActionPerformed(evt);
            }
        });

        CampoCantPag.setBackground(new java.awt.Color(240, 238, 240));
        CampoCantPag.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CampoCantPag.setForeground(new java.awt.Color(153, 153, 153));
        CampoCantPag.setText(" Cantidad de paginas");
        CampoCantPag.setPreferredSize(new java.awt.Dimension(165, 34));
        CampoCantPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoCantPagMouseClicked(evt);
            }
        });
        CampoCantPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantPagActionPerformed(evt);
            }
        });

        CampoPrecio.setBackground(new java.awt.Color(240, 238, 240));
        CampoPrecio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CampoPrecio.setForeground(new java.awt.Color(153, 153, 153));
        CampoPrecio.setText(" Precio ($)");
        CampoPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoPrecioMouseClicked(evt);
            }
        });
        CampoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecioActionPerformed(evt);
            }
        });

        CampoTitulo.setBackground(new java.awt.Color(240, 238, 240));
        CampoTitulo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CampoTitulo.setForeground(new java.awt.Color(153, 153, 153));
        CampoTitulo.setText(" Título");
        CampoTitulo.setDisabledTextColor(new java.awt.Color(110, 34, 83));
        CampoTitulo.setSelectionColor(new java.awt.Color(110, 34, 83));
        CampoTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoTituloMouseClicked(evt);
            }
        });

        CampoFecha.setBackground(new java.awt.Color(240, 238, 240));
        CampoFecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CampoFecha.setForeground(new java.awt.Color(153, 153, 153));
        CampoFecha.setText(" Fecha de lanzamiento");
        CampoFecha.setPreferredSize(new java.awt.Dimension(165, 34));
        CampoFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoFechaMouseClicked(evt);
            }
        });
        CampoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechaActionPerformed(evt);
            }
        });

        Encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/PanelAgregarLibro.png"))); // NOI18N

        jScrollPaneAreaDesc.setToolTipText("");

        AreaDesc.setBackground(new java.awt.Color(240, 238, 240));
        AreaDesc.setColumns(20);
        AreaDesc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        AreaDesc.setForeground(new java.awt.Color(153, 153, 153));
        AreaDesc.setRows(5);
        AreaDesc.setText("Descripción del producto");
        AreaDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AreaDesc.setFocusCycleRoot(true);
        AreaDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AreaDescMouseClicked(evt);
            }
        });
        jScrollPaneAreaDesc.setViewportView(AreaDesc);

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonAgregar.png"))); // NOI18N
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarMouseExited(evt);
            }
        });

        jTabbedPane.setBackground(new java.awt.Color(218, 216, 218));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Añadir.setBackground(new java.awt.Color(218, 216, 218));
        Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonNuevoAutor.png"))); // NOI18N
        Añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AñadirMouseExited(evt);
            }
        });

        listaAutores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(listaAutores);

        jLabel1.setText("Lista de autores");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Añadir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)))
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Añadir)
                .addGap(18, 18, 18))
        );
        jLayeredPane1.setLayer(Añadir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane.addTab("Autor", jLayeredPane1);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tapa"));

        jButton2.setText("limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelImagen.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelImagenLayout = new javax.swing.GroupLayout(jPanelImagen);
        jPanelImagen.setLayout(jPanelImagenLayout);
        jPanelImagenLayout.setHorizontalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanelImagenLayout.setVerticalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(64, 64, 64)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Primeras páginas"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jLayeredPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane.addTab("Carga Libro", jLayeredPane2);

        jPanel1.setBackground(new java.awt.Color(240, 238, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jComboBox1.setBackground(new java.awt.Color(218, 216, 218));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Idioma: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout AgregarLibroPanelLayout = new javax.swing.GroupLayout(AgregarLibroPanel);
        AgregarLibroPanel.setLayout(AgregarLibroPanelLayout);
        AgregarLibroPanelLayout.setHorizontalGroup(
            AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLibroPanelLayout.createSequentialGroup()
                .addComponent(Encabezado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AgregarLibroPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLibroPanelLayout.createSequentialGroup()
                        .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneAreaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AgregarLibroPanelLayout.createSequentialGroup()
                                .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoCantPag, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(CampoIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(CampoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CampoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(CampoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))))
                        .addGap(29, 29, 29))
                    .addGroup(AgregarLibroPanelLayout.createSequentialGroup()
                        .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarLibroPanelLayout.createSequentialGroup()
                                .addComponent(Agregar)
                                .addGap(14, 14, 14)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AgregarLibroPanelLayout.setVerticalGroup(
            AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLibroPanelLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCantPag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AgregarLibroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPaneAreaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarLibroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AgregarLibroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIsbnActionPerformed

    private void AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseEntered
        // TODO add your handling code here:
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonAgregarFocus.png")));
    }//GEN-LAST:event_AgregarMouseEntered

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseExited
        // TODO add your handling code here:
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonAgregar.png")));
    }//GEN-LAST:event_AgregarMouseExited

    private void CampoIsbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoIsbnMouseClicked
        // TODO add your handling code here:
        
        if (click1) {
            CampoIsbn.setText(null);
            click1=false;
            CampoIsbn.setForeground(Color.black);
    }
    }//GEN-LAST:event_CampoIsbnMouseClicked

    private void CampoCantPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoCantPagMouseClicked
        // TODO add your handling code here:
        if (click2) {
            CampoCantPag.setText(null);
            click2=false;
            CampoCantPag.setForeground(Color.black);
    }
    }//GEN-LAST:event_CampoCantPagMouseClicked

    private void CampoTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoTituloMouseClicked
        // TODO add your handling code here:
        if (click3) {
            CampoTitulo.setText(null);
            click3=false;
            CampoTitulo.setForeground(Color.black);
    }
    }//GEN-LAST:event_CampoTituloMouseClicked

    private void CampoPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoPrecioMouseClicked
        // TODO add your handling code here:
        if (click4) {
            CampoPrecio.setText(null);
            click4=false;
            CampoPrecio.setForeground(Color.black);
    }
    }//GEN-LAST:event_CampoPrecioMouseClicked

    private void CampoFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoFechaMouseClicked
        // TODO add your handling code here:
        if (click5) {
            CampoFecha.setText(null);
            click5=false;
            CampoFecha.setForeground(Color.black);
    }
    }//GEN-LAST:event_CampoFechaMouseClicked

    private void AreaDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaDescMouseClicked
        // TODO add your handling code here:
        if (click7) {
            AreaDesc.setText(null);
            click7=false;
            AreaDesc.setForeground(Color.black);
    }
    }//GEN-LAST:event_AreaDescMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CampoCantPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCantPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCantPagActionPerformed

    private void CampoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        VA.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelImagen.removeAll();
        jPanelImagen.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        m.Abrir_Dialogo(jPanelImagen);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirMouseExited
        // TODO add your handling code here:
        Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonNuevoAutor.png")));
    }//GEN-LAST:event_AñadirMouseExited

    private void AñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirMouseEntered
        // TODO add your handling code here:
        Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cookbookinterfaz/imagen/Resource/ButtonNuevoAutorFocus.png")));
    }//GEN-LAST:event_AñadirMouseEntered

    private void AñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirMouseClicked
        // TODO add your handling code here:
        AgregarAutor AA=new AgregarAutor(this);
        AA.setLocationRelativeTo(this);
        AA.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_AñadirMouseClicked

    private void CampoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    
  metodos m=new metodos();  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JPanel AgregarLibroPanel;
    private javax.swing.JTextArea AreaDesc;
    private javax.swing.JLabel Añadir;
    private javax.swing.JTextField CampoCantPag;
    private javax.swing.JTextField CampoFecha;
    private javax.swing.JTextField CampoIsbn;
    private javax.swing.JTextField CampoPrecio;
    private javax.swing.JTextField CampoTitulo;
    private javax.swing.JLabel Encabezado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAreaDesc;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JList listaAutores;
    // End of variables declaration//GEN-END:variables
}
