/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cookbookinterfaz;

/**
 *
 * @author Manu
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaAdminPanel = new javax.swing.JPanel();
        BotonAgregarLibro = new javax.swing.JButton();
        BotonVisualizarLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Administrador");
        setResizable(false);

        VentanaAdminPanel.setBackground(new java.awt.Color(218, 216, 218));

        BotonAgregarLibro.setText("agregar libro");
        BotonAgregarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarLibroMouseClicked(evt);
            }
        });

        BotonVisualizarLibros.setText("visualizar libros");
        BotonVisualizarLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVisualizarLibrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentanaAdminPanelLayout = new javax.swing.GroupLayout(VentanaAdminPanel);
        VentanaAdminPanel.setLayout(VentanaAdminPanelLayout);
        VentanaAdminPanelLayout.setHorizontalGroup(
            VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaAdminPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(BotonAgregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(BotonVisualizarLibros)
                .addGap(60, 60, 60))
        );
        VentanaAdminPanelLayout.setVerticalGroup(
            VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaAdminPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(VentanaAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregarLibro)
                    .addComponent(BotonVisualizarLibros))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarLibroMouseClicked
        // TODO add your handling code here:
        AgregarLibro AL=new AgregarLibro(this);
        AL.setLocationRelativeTo(this);
        AL.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_BotonAgregarLibroMouseClicked

    private void BotonVisualizarLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVisualizarLibrosMouseClicked
        // TODO add your handling code here:
        ListadoLibros LL=new ListadoLibros(this);
        LL.setVisible(true);
        LL.setLocationRelativeTo(this);
        this.setEnabled(false);
    }//GEN-LAST:event_BotonVisualizarLibrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarLibro;
    private javax.swing.JButton BotonVisualizarLibros;
    private javax.swing.JPanel VentanaAdminPanel;
    // End of variables declaration//GEN-END:variables
}
